In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [48]:
import os
import math
import random
import torch
from torch import nn
import torch.nn.functional as F

In [3]:
x = torch.randn(10)
x

tensor([ 1.8188,  1.8875,  0.9543, -0.1369, -0.8547,  0.4610, -0.3833,  0.1652,
        -0.9616, -0.3159])

In [4]:
y = sum(x)
y

tensor(2.6345)

In [5]:
y//10

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  """Entry point for launching an IPython kernel.


tensor(0.)

In [6]:
z = 0
for i in x:
  z += (sum(x)/len(x) - i)*(sum(x)/len(x) - i)
z

tensor(9.2479)

In [7]:
torch.mean(x)

tensor(0.2634)

In [8]:
sum(x)/len(x)

tensor(0.2634)

In [9]:
t = torch.sqrt(z/10)
t

tensor(0.9617)

In [10]:
torch.std(x)

tensor(1.0137)

In [11]:
W = torch.randn(5,10)
W

tensor([[ 0.5133, -0.3382,  0.8190,  0.8322,  0.5501,  0.4073, -0.1341,  1.4136,
         -0.3738,  0.3490],
        [ 0.1220,  1.0471, -0.3457, -0.1305, -1.0695,  1.0985, -1.8324, -1.3271,
         -0.1838,  1.6486],
        [-1.1090, -2.4007,  0.7148, -1.3409, -0.6531,  0.0210, -0.0832, -0.2304,
         -0.4384,  0.1760],
        [ 0.1760, -1.3214, -1.6942,  1.8101,  0.6828,  1.0772,  0.4304, -0.7256,
         -0.1684, -1.2278],
        [ 1.2225,  0.5395,  1.5644,  0.1653, -0.3276,  0.3423,  0.4641,  0.5210,
         -1.0594, -0.2025]])

In [12]:
y = W @ x
y

tensor([ 1.2147,  3.4457, -4.7550, -3.8608,  6.1409])

In [13]:
y2 = torch.matmul(W,x)
y2

tensor([ 1.2147,  3.4457, -4.7550, -3.8608,  6.1409])

In [14]:
zipWrow1x = zip(W[0], x)
zipWrow1x

In [15]:
for c,d in zipWrow1x:
  print(c,d)

tensor(0.5133) tensor(1.8188)
tensor(-0.3382) tensor(1.8875)
tensor(0.8190) tensor(0.9543)
tensor(0.8322) tensor(-0.1369)
tensor(0.5501) tensor(-0.8547)
tensor(0.4073) tensor(0.4610)
tensor(-0.1341) tensor(-0.3833)
tensor(1.4136) tensor(0.1652)
tensor(-0.3738) tensor(-0.9616)
tensor(0.3490) tensor(-0.3159)


In [16]:
y_1 = sum(c*d for c,d in zip(W[0], x))
y_1

tensor(1.2147)

In [18]:
x = torch.randn(512)
for i in range(100):
  a = torch.randn(512, 512)
  x = a @ x
x.mean(), x.std()

(tensor(nan), tensor(nan))

In [19]:
x = torch.randn(512)
for i in range(100):
  a = torch.randn(512, 512)
  x = a @ x
  if torch.isnan(x.std()):
    break
i

27

In [20]:
y = torch.randn(5)
y

tensor([-0.2727, -1.4137, -0.3468,  0.5189,  0.4212])

In [21]:
y.mean()

tensor(-0.2186)

In [22]:
y.std()

tensor(0.7747)

In [24]:
y2 = torch.randn(5) * 0.01
y2

tensor([-0.0140, -0.0059,  0.0135, -0.0025,  0.0148])

In [25]:
y2.mean(), y2.std()

(tensor(0.0012), tensor(0.0126))

In [26]:
x = torch.randn(512)
for i in range(100):
  a = torch.randn(512, 512) * 0.01
  x = a @ x
x.mean(), x.std()

(tensor(0.), tensor(0.))

In [29]:
x = torch.randn(512)
a = torch.randn(512, 512)
y = a @ x
y.mean()

tensor(-0.5183)

In [30]:
y.mean().item()

-0.5183464288711548

In [42]:
z = torch.randn(5)
z_deviations_from_mean = (z.mean() - z)*(z.mean() - z)
z_deviations_from_mean

tensor([0.0074, 0.4165, 1.0863, 0.8492, 1.9723])

In [43]:
z_sum_of_deviations = sum(z_deviations_from_mean)
z_sum_of_deviations

tensor(4.3317)

In [44]:
z_var = z_sum_of_deviations.item() / 4
z_var

1.082927942276001

In [45]:
(z.std()*z.std()).item()

1.0829278230667114

In [46]:
z.pow(2).std()

tensor(1.7114)

In [47]:
z.pow(2).mean().item()

1.2534716129302979

In [49]:
mean, var = 0., 0.
for i in range(10):
  x = torch.randn(512)
  a = torch.randn(512, 512)
  y = a @ x
  mean += y.mean().item()
  var += y.pow(2).std().item()
mean/10, math.sqrt(var/10)

(-0.1266657903790474, 26.150630486730442)

In [50]:
math.sqrt(512)

22.627416997969522

In [51]:
mean, var = 0., 0.
for i in range(100):
  x = torch.randn(512)
  a = torch.randn(512, 512)
  y = a @ x
  mean += y.mean().item()
  var += y.pow(2).std().item()
mean/100, math.sqrt(var/100)

(-0.05458742506802082, 27.105116706713705)

In [53]:
mean, var = 0., 0.
for i in range(10000):
  x = torch.randn(512)
  a = torch.randn(512, 512)
  y = a @ x
  mean += y.mean().item()
  var += y.pow(2).std().item()
mean/10000, math.sqrt(var/10000)

(-0.00734777318648994, 26.866570069769658)

In [54]:
v = torch.randn(5)
v_var = v.pow(2).std()
v_var

tensor(1.5943)

In [55]:
v_var2 = v.pow(2).mean()
v_var2

tensor(1.6959)

In [56]:
v, v.pow(2), v.pow(2).mean()

(tensor([ 1.1873, -1.8876,  1.7654,  0.0105,  0.6246]),
 tensor([1.4097e+00, 3.5630e+00, 3.1166e+00, 1.0927e-04, 3.9009e-01]),
 tensor(1.6959))

In [59]:
v.std(), v.pow(2).std()

(tensor(1.4055), tensor(1.5943))

In [61]:
sum(v.pow(2)).item()/5

1.695892906188965

In [62]:
v.mean(), v.pow(2).mean()

(tensor(0.3400), tensor(1.6959))

In [63]:
mean, var = 0., 0.
for i in range(10000):
  x = torch.randn(512)
  a = torch.randn(512, 512)
  y = a @ x
  mean += y.mean().item()
  var += y.pow(2).mean().item()
mean/10000, math.sqrt(var/10000)

(0.0027189633348956702, 22.61597596300357)

In [64]:
math.sqrt(512)

22.627416997969522

In [65]:
mean, var = 0., 0.
for i in range(10000):
  x = torch.randn(512)
  a = torch.randn(512, 512) * math.sqrt(1. / 512)
  y = a @ x
  mean += y.mean().item()
  var += y.pow(2).mean().item()
mean/10000, math.sqrt(var/10000)

(-0.0006281847209553234, 0.9996240616644094)

In [66]:
x = torch.randn(512)

for i in range(100):
  a = torch.randn(512, 512)
  x = a @ x
x.mean(), x.std()

(tensor(nan), tensor(nan))

In [67]:
x = torch.randn(512)

for i in range(100):
  a = torch.randn(512, 512) * math.sqrt(1./512)
  x = a @ x
x.mean(), x.std()

(tensor(-0.0379), tensor(0.7111))

In [69]:
x = torch.randn(512)

for i in range(100):
  a = torch.randn(512, 512) * math.sqrt(1./512)
  x = torch.tanh(a @ x)
x.mean(), x.std()

(tensor(0.0002), tensor(0.0563))

In [77]:
x = torch.randn(512)
for i in range(100):
  a = torch.randn(512, 512).uniform_(-1,1) * math.sqrt(1./512)
  x = torch.tanh(a @ x)
x.mean(), x.std()

(tensor(-7.7337e-26), tensor(8.0619e-25))

In [78]:
def xavier(m,n):
  return torch.Tensor(m,n).uniform_(-1, 1) * math.sqrt(6./(m+n))

x = torch.randn(512)

for i in range(100):
  a = xavier(512,512)
  x = torch.tanh(a @ x)
x.mean(), x.std()

(tensor(-0.0037), tensor(0.0603))

In [79]:
def relu(x):
  return x.clamp_min(0.)

In [83]:
relu(torch.randn(5))

tensor([0.0000, 0.0000, 0.0000, 0.8360, 0.0000])

In [84]:
x = torch.randn(512)

for i in range(100):
  a = xavier(512,512)
  x = relu(a @ x)
x.mean(), x.std()

(tensor(5.2402e-16), tensor(7.6631e-16))

In [85]:
def kaiming(m,h):
  return torch.randn(m,h)*math.sqrt(2./m)

In [86]:
x = torch.randn(512)

for i in range(100):
  a = kaiming(512,512)
  x = relu(a @ x)
x.mean(), x.std()

(tensor(0.7625), tensor(1.1621))